### ISSUE TITLE
MarkerOptions 缺少 anchor 参数

### ISSUE THREAD

**Issue by fourcels** [breeze9527/amap-js-api-workspace#1]
https://lbs.amap.com/api/javascript-api/reference/overlay#marker

MarkerOptions | 类型 | 说明
-- | -- | --
anchor | String | 设置点标记锚点。<br>默认值：'top-left' <br>可选值：'top-left'\|'top-center'\|'top-right'\|'middle-left'\|'center'\|'middle-right'\|'bottom-left'\|'bottom-center'\|'bottom-right'（自v1.4.13 新增）

**Comment by breeze9527** [comment]
感谢反馈，1.4.13的新增功预计将会在这周内更新并同步到@types，但具体时间取决于DefinitelyTyped合并的PR的速度，目前可以使用以下代码做临时的fixed
```typescript
```

**Comment by breeze9527** [comment]
@fourcels npm已经同步了

**Comment by fourcels** [comment]
@breeze9527 thank you
